#!/bin/bash
mkdir -p train

python3 object_detection/legacy/train.py \
    --logtostderr \
    --pipeline_config_path=config/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.config \
    --train_dir=train \

